In [1]:
import torch

In [2]:
tensor = torch.ones(3,3)

In [3]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
tensor.view(9)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
torch.add(tensor,tensor)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [8]:
tensor.sub(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
tensor.mul(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.mul(tensor,tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.div(tensor,tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
tensor.div(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
tensor = torch.tensor([1,2,3,4,5])

In [27]:
tensor

tensor([1, 2, 3, 4, 5])

In [32]:
tensor=tensor.float()

In [33]:
tensor.mean()

tensor(3.)

In [34]:
tensor.std()

tensor(1.5811)